services:
  db:
    image: postgres:16-alpine
    container_name: template-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: template_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: template-mailpit
    restart: always
    ports:
      - '1025:1025'
      - '8025:8025'

volumes:
  pgdata:
